### ISSUE TITLE
Maze Generator Issue with UE5.1, perhaps user error. but

### ISSUE THREAD

**Issue by EdwardWelborn** [1owkeyme/UE5-MazeGeneratorPlugin#13]
Perhaps I am doing this wrong,   I drop the BP onto UE5.1 and set the size.  When in the editor it looks right except part of the walls are not drawing correctly. 
When I run the level, the maze continuously  redraws the maze, instead of the maze that I dropped on the setup.
HELP, probably me doing something wrong.
![mazegeneratorissue](https://user-images.githubusercontent.com/45338915/205536656-e404a022-0bb5-4183-9663-0164c8177e64.jpg)

**Comment by 1owkeyme** [comment]
Hi!
In the BP_Maze there is some loop logic that being executed (for example
sake).
 Hope this helps!

**Comment by 1owkeyme** [comment]
And by the way. Your wall mesh should be "square", i.e. the same on all sides!
